#!/usr/bin/env bash
#script that transfers a file from client to a server over ssh
if [ $# -gt 3 ]
then
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
