#!/usr/bin/env bash
#install nginx and sets index.html to Holberton School
sudo apt update -y
sudo apt install nginx -y
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
