#!/usr/bin/env bash
#this script installs nginx and configure a redirection at server-ip/redirect_me
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start

config="\terror_page 404 \/error_404.html;\n
\tlocation = \/error_404.html {
\t\troot \/usr\/share\/nginx/html;
\t\tinternal;
\t}"
sed -i "19i $config" /etc/nginx/sites-enabled/default
sudo service nginx restart

