#!/usr/bin/env bash
#this script installs nginx and configure a redirection at server-ip/redirect_me
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo service nginx start

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404.html
config="\\\terror_page 404 \/error_404.html;"
configloc="\n\tlocation = \/error_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "19a $config$configloc" /etc/nginx/sites-enabled/default
sudo service nginx restart

