#!/usr/bin/env bash
#script that setup nginx and adds custom http response request to nginx.config
sudo apt update -y
sudo apt install nginx -y
sudo sed -i '12i\	add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx start
