#!/usr/bin/env bash
#HAproxy install and config
sudo apt -y update
sudo apt -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

config_file=/etc/haproxy/haproxy.cfg

sudo sed -i '$a\listen 1122-lb-01\n\tbind *:80\n\tmode http\n\tstats enable' $config_file
sudo sed -i '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $config_file
sudo sed -i '$a\\tserver 1122-web-01 35.243.161.56:80\n\tserver 1122-web-02 54.163.0.167:80' $config_file
sudo /etc/init.d/haproxy start
