#!/usr/bin/env bash
#HAproxy install and config

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

config_file=/etc/haproxy/haproxy.cfg

echo -e "listen 1122-lb-01
	bind *:80
	stats enable
	balance roundrobin
	server 1122-web-01 35.243.161.56:80 check
	server 1122-web-02 35.229.16.85:80 check" >> $config_file

sudo service haproxy restart
