#!/usr/bin/env bash
#script that sets listen port of nginx to port 80 instead of 8080
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
/etc/init.d/nginx restart
kill "$(pgrep -o nginx)"
