#!/usr/bin/env bash
#display a sentence indefinitely and creates a file with process pid
#Behave differently on each Signal recieved
echo $$ > /var/run/holbertonscript.pid
while true
do
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; quit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
echo "To infinity and beyond"
sleep 2
done
