#!/usr/bin/env bash
flist='1-for_holberton_school 2-while_holberton_school 3-until_holberton_school 4-if_9_say_hi 5-4_bad_luck_8_is_your_chance 6-superstitious_numbers 7-clock 8-for_ls 9-to_file_or_not_to_file 10-fizzbuzz 100-read_and_cut'
for i in $flist
do
	touch $i
done
chmod u+x *
chmod u-x README.md
