#!/usr/bin/env bash
#script that does previous task in 7 lines or less
pkill apache2
chmod 766 /etc/nginx/nginx.conf
sed -i "1,30s/80/8080" /etc/nginx/sites-enabled/default
sudo u- nginx service nginx restart
