#!/usr/bin/env bash
#script that does previous task in 7 lines or less
pkill apache2
sed -i "1,30s/80/8080/" /etc/nginx/sites-enabled/default
chmod 744 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
